### PR TITLE
The emmyballot project now works with multiple years of emmyballots

### PR DESCRIPTION
**Pull request by freejoe76**
Changes were made to:
1. Publish emmy polls for multiple years.
2. Use the database only when necessary.
3. Make database creation easier.
4. Configure how it works on a year-by-year basis.

### CODE REVIEW

**Comment by tommeagher** [comment]
Hey, Joe. Awesome. Thank you! 
Let me take a quick run through the new commits. Might take me a few days to get to it, but then we'll merge. Thanks for contributing back to the project!

**Comment by freejoe76** [comment]
Yea -- I definitely made some project design decisions in the code here. I believe it's easier to re-use than when I started with it, I'm also totally willing to write more documentation explaining how to get it off the ground and use it in its two states, before the emmys and after.

**Comment by tommeagher** [comment]
Hey Joe, at a glance, this looks good. I asked @peggybustamante to take a look just to make sure there's nothing that would give us pause. Once she has a chance to do that, we'll merge. If you have any extra docs on bootstrapping the app, please feel free to commit. We'd be happy to have it. Stay tuned.

**Comment by davisshaver** [comment]
:rocket:

**Comment by tommeagher** [comment]
Joe, @peggybustamante took a look and gave this a :+1: I'm going to merge. Will make a couple small tweaks to the README, including adding DFM and 2013 to the license. 
If you have time to add some documentation on bootstrapping this elsewhere, that'd be awesome. Either way. Thanks for using this and for sharing your improvements!

**Comment by freejoe76** [comment]
@tommeagher thanks, and agreed -- there's more to be done with the instructions.

**Pull request merged**
